# Generated by Django 5.1.7 on 2025-03-31 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consolas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potencia_de_procesamiento', models.CharField(max_length=100)),
                ('capacidad_de_almacenamiento', models.CharField(max_length=100)),
                ('conectividad', models.CharField(max_length=100)),
                ('diseño_y_ergonomía', models.CharField(max_length=100)),
            ],
        ),
    ]
