# Generated by Django 5.1.7 on 2025-03-31 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuegos', '0002_videojuegos_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuegos',
            name='fecha_creacion',
            field=models.DateTimeField(),
        ),
    ]
