# Generated by Django 5.1.7 on 2025-03-31 22:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuegos', '0003_alter_videojuegos_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videojuegos',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='videojuegos',
            name='fecha_de_creacion',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
