# Generated by Django 5.1.7 on 2025-03-19 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='fecha_de_creacion',
            new_name='fecha_creacion',
        ),
    ]
